### ISSUE TITLE
appleKeyboard.h missing

### ISSUE THREAD

**Issue by turbolent** [RatRanch/Apple-Newton-Keyboard-USB-Adapter#1]
Great project, I've been looking for something like this for a while. I'd like to give this a try, where can I find the file 
 included in the sketch called `appleKeyboard.h`?

**Comment by RatRanch** [comment]
My bad.  I omitted the header file when I uploaded the project to github.

Corrected:  https://github.com/RatRanch/Apple-Newton-Keyboard-USB-Adapter <https://github.com/RatRanch/Apple-Newton-Keyboard-USB-Adapter>

Cheers,
-Jim

**Comment by turbolent** [comment]
This is great, thank you so much!
